# Generated by Django 3.2.7 on 2021-12-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211214_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default='SubTitle', max_length=150),
        ),
    ]
